AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Resources:
  SplayshAPIFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: main.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        SplayshAPI:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: ANY
      FunctionUrlConfig:
        AuthType: NONE

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SplayshAPIApi:
    Description: "API Gateway endpoint URL for Prod stage for SplayshAPI function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  SplayshAPIFunction:
    Description: "SplayshAPI Lambda Function ARN"
    Value: !GetAtt SplayshAPIFunction.Arn
  SplayshAPIFunctionIamRole:
    Description: "Implicit IAM Role created for SplayshAPI function"
    Value: !GetAtt SplayshAPIFunctionRole.Arn