name: Deploy SAM - DEV

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        type: string
        default: 'us-east-1

jobs:
  deploy:
    uses: ./.github/workflows/sam-pipeline.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      region: us-east-1
      environment: dev
