name: Deploy SAM - DEV

on:
  workflow_dispatch:
  push:
    branches:
      - develop


jobs:
  deploy:
    uses: ./.github/workflows/sam-pipeline.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      region: us-east-1
      environment: dev
