name: Deploy SAM - DEV

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    uses: ./.github/workflows/sam-pipeline.yml
    secrets: inherit
    with:
      region: us-east-1
      environment: dev
